[package]
name = "filedrop-v2"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*


[dependencies]
rocket = { version = "0.5.1" }
rocket-include-static-resources = "0.10.5"
fsio = "0.4.1"
dotenv = "0.15.0"
mime_guess = "2.0.5"
serde = "1.0.219"
serde_json = "1.0.140"
chrono = "0.4.40"

#FOLDER SUPPORT
zip = { version = "2.5.0"}
tempfile = "3.19.1"
walkdir = "2.5.0"
