## defaults for _all_ profiles
[default]
address = "0.0.0.0"
port = 8000
template_dir = "templates/"

#see "https://api.rocket.rs/v0.5-rc/rocket/config/struct.SecretKey.html" for more info about "secret_key"
#u can generate one with : `openssl rand -base64 32`
secret_key = "you'll have to replace that value"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]


## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
